<a href="https://colab.research.google.com/github/jahke318/Pytorch/blob/main/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.1+cu124


## Introduction to Tensors

### Creating Tensors
Tensors are created using torch.tensor()
    


In [ ]:
# scalar

scalar = torch.tensor(7)
scalar


tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# Get tensor back as a python int
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX


tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim
# dimensions = number of closing square brackets

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR
# these can be basically any size and any shape with a shit ton of #s
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape
# this shows that we  have 1 3x3 tensor
# python is zero indexed

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [ ]:
# num of dimensions

# scalar  0
# vector  1
# matrix  2
# tensor  00

## Random tensors

In [ ]:
# Why random tensors

# Random tensors are important because the way taht many neurel networks learn is that
# they start with tensors full of random numbers and then adjust those numbers to better
# represent the data

# Start with random numbers -> look at data -> updated random numbers -> look at data
#->update random rnumbers

In [ ]:
# Create a random tensors of size(3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.4177, 0.3731, 0.7475, 0.3424],
        [0.5026, 0.0118, 0.5918, 0.2755],
        [0.3852, 0.6943, 0.7424, 0.3903]])

In [ ]:
random_tensor.ndim
# these dimensions being the (3,4) so we get 2

2

In [ ]:
# create a random tensor with similar shape to an image tensor
# any data can be represented as a tensor and almost all images will have height, width, and RGB
random_image_size_tensor = torch.rand(size=(224,224, 3)) # these 3 values represent height, width, color chanel(RGB)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

## Zeros and ones

In [ ]:
# Create a tensors of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [ ]:
# use torch.range()/ use arange for start, end, step
one_to_100 = torch.arange(start = 1, end = 100, step = 2)

In [ ]:
torch.__version__

'2.5.1+cu124'

In [ ]:
ten_zeros = torch.zeros_like(input = one_to_100)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0])

### Tensor Data Types
There are 3 main errors with tensors
1. the tensor is not the right dtype
2. the tensor is not the right shape
3. the tensor is not on the right device

In [ ]:
# Float 32 tensor
# 32 is single precision
# 16 is half precision can calculate faster
# 64 is double precision
# you can not do things with tensors running on different devices
float_32_tensor = torch.tensor([2.0, 6.0, 9.0],
                               dtype=None,        # this is the data type of the tensor
                               device=None,       # Cpu, gpu, cooda, etc the device the tensor is on
                               requires_grad=False)# whether or not to track gradenets with this tensors operations
float_32_tensor

tensor([2., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
# How to change the type of tensor
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([2., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor
# some mathematical operations will return an error doing this but some will not

tensor([ 4., 36., 81.])

In [ ]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

### Getting information from tensors
the tensor is not the right dtype - to get the dtype use 'tensor.dtype'
the tensor is not the right shape - to get the shape use 'tensor.shape/siz'
the tensor is not on the right device - to get the device use 'tensor.device'

In [ ]:
# create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.1595, 0.1806, 0.0031, 0.6768],
        [0.5410, 0.2006, 0.0464, 0.0744],
        [0.7532, 0.5223, 0.2750, 0.6983]])

In [ ]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")  # by default the tensor will be on the cpu

tensor([[0.1595, 0.1806, 0.0031, 0.6768],
        [0.5410, 0.2006, 0.0464, 0.0744],
        [0.7532, 0.5223, 0.2750, 0.6983]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


### manipulating tensors (tensor operations)

Tensor operations include:
addition
subtraction
multiplication(element-wise)
Matrix multiplication
Division

In [ ]:
# Create a tensor
tensor = torch.tensor([1,2,3])
tensor + 10


tensor([11, 12, 13])

In [ ]:
# multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [ ]:
# subtract 10
tensor - 10

tensor([-9, -8, -7])

In [ ]:
# Try out pytorch built in function
# mul
# add

 ### Matrix Multiplication

 Two main ways of perfroming multiplication in nueral networks

 1. Element-wise multiplication
 2. Matrix multiplication (dot product)(@ = matmul)

 There are 2 main rules that performing matrix multiplication needs to stisfy:
 1. The **INNER DIMENSIONS** must match
 - (3,2) @ (3,2) this will not work
 - (3,2) @ (2,3) this will work
 - the resulting matrix will have the dimesnions of the outside dim so (3,3)

In [ ]:
# Element wise multiplication
print(tensor, "*" ,tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
tensor

tensor([1, 2, 3])

In [ ]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [ ]:
# This is an example of doing matrix multiplication through a for loop which is slower than the method below
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)


In [ ]:
# Matrix multiplication is MUCH faster this way b using matmul
torch.matmul(tensor, tensor)

tensor(14)

### One of the most common errors in deep learnign is shape errors


In [7]:
# Shapes for matrix multiplication

tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])


tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])


# mm stands for mat mul or matrix multiplication
# these can not be mm because the inner dimensions do not match
torch.mm(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [13]:
# To fix our tensor shape issues we can manipulate the shape of one of our tensors using a **transpose**

# A transpose switches the axes or dimensions of a given tensor
# the .T stands for transpose
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [15]:
# Now that we have reshaped it we can multiply them
# tensor a times tensor b.T
# We can multiply because the dimesnions are now 2x3 and 3x2
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

### Tensor aggregation: finding the min, max, mean, sum, etc




In [32]:
# Create a tensor
x= torch.arange(1,100,10)


In [24]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [26]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [28]:
# Find the mean
# we need our tensors to be the right data type
# X is a long data type and we need a floating point data type or a complex dtype

# this is how we convert to float 32
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

### Find the positional min and max

In [33]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [38]:
# Find the position in the tensor that has the min value with argmin() -> returns index position of target tensor where min val occurs
x.argmin()

tensor(0)

In [39]:
# index of min
x[0]

tensor(1)

In [40]:
# Find the position in the tensor that has the max value with argmax() -> returns index position of target tensor where max val occurs
x.argmax()

tensor(9)

In [42]:
# index of max
x[9]


tensor(91)

In [ ]:
# to start everything back up again after we take a break we can go to runtime and click reconnect and run all
# we can also run after a given cell if we want to leave it to show the error

In [ ]:
## Reshaping, stacking, squeezingm and unsqueezing tensors

* Reshaping -